name: Context Variable Example
on: 
  push: 
    branches: main

jobs:
  Context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: printing details
        run: |
          echo "${{ github.actor }}'s push is merged into main of repo: ${{github.repository}}"
          echo "Demo"

  All-vars:
    runs-on: ubuntu-latest
    steps:
      - name: printing all variables under github
        run: echo "${{ toJson(github) }}"

  Print-Envs:
    runs-on: ubuntu-latest
    steps:
      - name: printing all environmental variables
        run: env

      - name: printing current commit sha
        run: echo "$GITHUB_SHA"
