name: Output demo
on: 
  push: 
    branches: main

jobs:
  build:
    outputs:
      version-name: ${{ steps.stepone.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: stepone
        run: echo "version= 1.0.0" >> $GITHUB_OUTPUT

      - name: step2
        run: echo "The artifact version is ${{ steps.stepone.outputs.version }}"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: printing value from job build
        run: echo "The vesion is ${{ needs.build.outputs.version-name }}"
